apiVersion: config.kio.kasten.io/v1alpha1
kind: PolicyPreset
metadata:
  name: daily-policy-preset
  namespace: kasten-io
spec:
  comment: Policy preset for daily backup
  backup:
    frequency: '@daily'
    subFrequency:
      weekdays: [6]    
    backupWindow:
        start:
          hour: 22
          minute: 30
        end:
          hour: 7
          minute: 0          
    retention:
      daily: 7
      weekly: 4      
  export:
    frequency: '@daily'
    exportData:
      enabled: true
    profile:
      name: "{{ locprofile }}"
      namespace: kasten-io
    retention:
      daily: 7
      weekly: 4            